---
- name: Reload netdata health
  ansible.builtin.shell:
    cmd: |
      set -e
      id=$(docker ps -aq --filter 'name=^netdata$')
      [ -n "$id" ] || exit 0
      docker exec netdata netdatacli reload-health
  changed_when: true

- name: Restart netdata
  ansible.builtin.shell:
    cmd: |
      set -e
      id=$(docker ps -aq --filter 'name=^netdata$')
      [ -n "$id" ] || exit 0
      docker restart netdata
  changed_when: true
