---
- name: header-backup | Install LUKS header backup script
  ansible.builtin.copy:
    src: homelab-luks-header-backup
    dest: /usr/local/bin/homelab-luks-header-backup
    owner: root
    group: root
    mode: "0755"
