---
- name: target | Create homelab-services systemd target
  ansible.builtin.copy:
    dest: /etc/systemd/system/homelab-services.target
    mode: "0644"
    content: |
      [Unit]
      Description=Home Lab Services (requires /mnt/data)
      Requires=mnt-data.mount
      Wants=docker.service mnt-data-swapfile.swap
      After=mnt-data.mount docker.service

- name: target | Reload systemd
  ansible.builtin.systemd:
    daemon_reload: true
