[plugin:apps]
    update every = 5

[plugin:cgroups]
    update every = 5

[db]
    dbengine tier 0 retention size = 1024MiB
    dbengine tier 0 retention time = 5d

    dbengine tier 1 retention size = 1024MiB
    dbengine tier 1 retention time = 30d

    dbengine tier 2 retention size = 1024MiB
    dbengine tier 2 retention time = 10mo

[health]
    health log retention = 60d

    in memory max health log entries = 5000
