---
- name: packages | Remove unused network services and legacy clients (CIS 2.1.x, 2.2.x)
  ansible.builtin.apt:
    name:
      - avahi-daemon
      - telnet
      - ftp
    state: absent
    purge: true
    autoremove: true
